### PR TITLE
Choice of test cases for the paper

### PR DESCRIPTION
**Pull request by aimalz**
I've revised the paper draft based on feedback from @drphilmarshall.  This pull request is specifically for Sec. 3 in [the draft](https://github.com/aimalz/chippr/blob/issue/41/reboot_paper/research/paper/draft.pdf).  The tests outlined there were implemented in [the previous version](https://github.com/aimalz/prob-z/nz) but (mostly) not in [the current version](https://github.com/aimalz/chippr).  I want to finalize the choice of tests to include in the paper so I don't waste time implementing simulation options that won't make it to publication.  **Are there any other tests I should include in the paper?  Are there any tests on this list that should not be in the paper?**

### CODE REVIEW

**Comment by aimalz** [comment]
@drphilmarshall Thank you very much for the speedy feedback!  I'll get back into implementing simulations for the outlined test cases this week.  Re: writing, thanks for finding those instances of the passive voice and inconsistent tenses.  I agree with you on both points and apologize for the sloppy writing.  I'll fix that ASAP.

**Comment by drphilmarshall** [comment]
No need to apologize. Writing scientific papers is already a skill; writing
them continuously as the research proceeds is another level of difficulty.
I guess figuring our what your convention is going to be (eg active voice,
"we do this in general, we did this in particular") and then sticking makes
sure that the paper remains understandable by the passing reader whatever
stage in its development it is at.

**Comment by davidwhogg** [comment]
...and I'm not sure @drphilmarshall and I would even agree on the basics. For example, although I agree on active voice, I think the subjects of the sentences should be parts of the Universe and the data, not astronomers, where possible.

**Comment by drphilmarshall** [comment]
@davidwhogg No, I agree: we should afford both the data and the Universe
all due respect :-)

**Pull request merged**
