### PR TITLE
Issue/30/mcmc diagnostics

### PR DESCRIPTION
**Pull request by aimalz**
This branch is totally overloaded with changes that really need to be merged in before continuing.  Now is the time!

### CODE REVIEW

**Comment by aimalz** [comment]
That's a very good question.  I think my goals with this are to have something that [ ] runs, [ ] gives normalized results for all estimators, and [ ] includes all the diagnostic plots I implemented in this branch.

**Comment by drphilmarshall** [comment]
Sounds good to me. Let's get the paper under continuous build with PDF
posted to an orphan `pdf` branch then, so you can point us to the plots
efficiently when you are ready.

**Comment by aimalz** [comment]
Wow, that was way easier than I expected.  I should clean up the garbage in the comments and check that the docstrings still match the content, but other than that, I think this branch may be ready for review.

**Comment by aimalz** [comment]
I think everything is ready for merging.  If it isn't offensive to you @drphilmarshall, I can merge this without review (because impatience).  Also, I don't think I should be asking anyone else to dig through such a big PR anyway.

**Comment by drphilmarshall** [comment]
Good executive decision, much appreciated! Thanks :-)

**Pull request merged**
